# Name of the dictionary file used to source words definitions
# The dictionary file must follow the JIJI format => https://github.com/juliango202/jiji
dictionary: jiji.jmdict.yaml

# Font-size to use when writing dictionary definitions
# A low resolution video will need a higher font-size, and vice-versa
definitionSize: 9

# List of colors to use successively to highlight the defined words in a subtitle caption.
# To turn off highlighting, just use one value corresponding to white => '#FFFFFF'
highlightColors:
- '#FFAAAA'
- '#AAAAFF'
- '#AAFFAA'
- '#FFAAFF'
- '#AAFFFF'

# Flag to display all lemmas of a defined word or not.
# When a dictionary definition is associated with several lemmas(e.g. アップデート, アップデイト),
# you can set this option to true to display them all
# otherwise set to false(default) to display only the lemma that appears in the caption
displayOtherLemma: false

# Ignore words if their frequency is one of the list.
# => When the information is available in the dictionary, each word is tagged with a "frequency" rank
# Frequency goes from 1(very frequent) to 12(rare)
# The list below is a list of frequency rank to ignore when extracting definitions
# This is usually used to hide the definitions of very frequent words when you expect to know them already
# NOTE: frequency information while helpfull is often missing and not always reliable
ignoreFrequencies:
- 1

# Ignore words in the list below
# You can put here the list of words that you already know and thus don't want defined
ignoreWords:
- あ
- ああ
- あい
